### ISSUE TITLE
Bundle lycoris_lora in docker image

### ISSUE THREAD

**Issue by UuuNyaa** [aoirint/sd-scripts-docker#8]
Hi!

I am installing and using [lycoris_lora](https://github.com/KohakuBlueleaf/LyCORIS) in sd-scripts-docker with the following script:
```bash
cat > Dockerfile << __EOF__
FROM aoirint/sd_scripts
RUN gosu user pip3 install --no-cache-dir lycoris_lora
__EOF__

docker run --rm --gpus all \
    -v "./base_model:/base_model" \
    -v "./work:/work" \
    -v "./cache/huggingface/hub:/home/user/.cache/huggingface/hub" \
    $(docker build -q .) \
    ... snip ...
    --network_module lycoris.kohya \
    ... snip ...
```

lycoris_lora is an additional network module for sd-scripts, and the installed image size increase is very small (568 kB).

```bash
docker inspect -f "{{.Size}}" 41a3c297271e 4fa8200b50be
17662514408
17661946303
```

So I think we have no problem bundling lycoris_lora into sd-scripts-docker.
Is it against the policy of this repository to bundle lycoris_lora in the docker image?

**Comment by aoirint** [comment]
Thanks for your nice suggestion!

It seems no problem for this repository's policy to bundle `lycoris_lora`.
I will try to work on it. I would appreciate your help to confirm that it works.

- PyPI: [lycoris-lora](https://pypi.org/project/lycoris-lora/)
- GitHub: [KohakuBlueleaf/LyCORIS](https://github.com/KohakuBlueleaf/LyCORIS)

And thanks for investigating the image size information as well!
I am not too concerned about bundle size since CUDA is so large.

**Comment by UuuNyaa** [comment]
Thank you for starting work so quickly.
I will test it when I have time.

> I am not too concerned about bundle size since CUDA is so large.

Switching the cuda image from `devel` to `runtime` would reduce the image size by 3GB.

```
nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04 2.04 GB
nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04   5.03 GB
```

This is a different topic than this issue, but please consider it.

**Comment by aoirint** [comment]
I have created a (pre)release including `lycoris_lora` v1.9.0.

- https://github.com/aoirint/sd-scripts-docker/releases/tag/20231103.1

```shell
sudo docker run --rm --gpus all aoirint/sd_scripts:20231103.1
```

Please reopen this issue or create a new issue if LyCORIS training does not work.

> Switching the cuda image from devel to runtime would reduce the image size by 3GB.

Thanks for the information. I will check to see if it is possible to switch to `runtime` base image for a large size reduction.
